name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # or your deployment branch

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
          username : ${{secrets.DOCKER_USERNAME}}
          password : ${{secrets.DOCKER_TOKEN}}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/projects:version1 .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/projects:version1
